name: dmu
description: A command-line tool to manage Git dependencies as local packages in Dart/Flutter projects. Streamline your multi-repo development workflow.
version: 1.0.0
repository: https://github.com/pretodev/dmu
issue_tracker: https://github.com/pretodev/dmu/issues
homepage: https://github.com/pretodev/dmu

executables:
  dmu:

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  yaml: ^3.1.2
  args: ^2.4.2
  io: ^1.0.4
  process: ^5.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
