name: syncpack
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  yaml: ^3.1.2
  args: ^2.4.2
  io: ^1.0.4
  process: ^5.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
